### ISSUE TITLE
Jupyter: stratifySpatial doesn't work

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/ASKE-E#14]
If I try a basic `stratifySpatial` example in Jupyter, it fails thusly:

```
> sirESL = loadESL("sir.esl")

> sirESL

model SIR:
  let beta = 0.4
  let gamma = 0.04

  let s_initial = 997
  let i_initial = 3
  let r_initial = 0

  state S = s_initial
  state I = i_initial
  state R = r_initial

  let total_population = S + I + R

  assert total_population == s_initial + i_initial + r_initial # total population is constant

  event Infect:
    rate: 
      beta * S * I / total_population
    effect:
      S -= 1
      I += 1
      
  event Remove:
    rate: 
      gamma * I
    effect:
      I -= 1
      R += 1
      
      

> sea_pdx_sir = stratifySpatial(sirESL, "connectionGraph/cities.txt")

Traceback (most recent call last):
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 646, in do_execute
    self.interpreter.evalStmt(parsed, outputs)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 608, in evalStmt
    self.env[stmt.name] = self.evalExpr(stmt.expr, output)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 602, in evalExpr
    return self.callFn(expr, output)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 563, in callFn
    return self.builtins[call.functionName](call, output)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 327, in stratifySpatial
    stratResult = self.donu.stratifySpatial(model.source, cgraph.value, call)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 233, in stratifySpatial
    return self.request(req)['model']
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 168, in request
    raise Exception("Call to donu failed - response text: " + response.text)
Exception: Call to donu failed - response text: readCreateProcess: curl "-X" "POST" "-H" "Content-type: application/json" "-d" "{\"top\":{\"O\":[{\"os\":2,\"ot\":1},{\"os\":3,\"ot\":2}],\"T\":[{\"tname\":\"Infect\"},{\"tname\":\"Remove\"}],\"I\":[{\"it\":1,\"is\":1},{\"it\":2,\"is\":2}],\"S\":[{\"sname\":\"S\"},{\"sname\":\"I\"},{\"sname\":\"R\"}]},\"conn\":{\"V\":[{},{}],\"E\":[{\"tgt\":2,\"src\":1},{\"tgt\":1,\"src\":2}]},\"type\":\"spat\"}" "localhost:8001" (exit 7): failed
```

The server produces this output:

```
127.0.0.1 - - [01/Jun/2021:13:31:59 -0400] "POST / HTTP/1.1" 400 446 - "python-requests/2.25.1"
CheckModel (CheckModelCommand {checkModelModel = ModelDef {modelDefSource = Inline "model SIR:\n  let beta = 0.4\n  let gamma = 0.04\n\n  let s_initial = 997\n  let i_initial = 3\n  let r_initial = 0\n\n  state S = s_initial\n  state I = i_initial\n  state R = r_initial\n\n  let total_population = S + I + R\n\n  assert total_population == s_initial + i_initial + r_initial # total population is constant\n\n  event Infect:\n    rate: \n      beta * S * I / total_population\n    effect:\n      S -= 1\n      I += 1\n      \n  event Remove:\n    rate: \n      gamma * I\n    effect:\n      I -= 1\n      R += 1\n      \n      ", modelDefType = AskeeModel}})
127.0.0.1 - - [01/Jun/2021:13:40:09 -0400] "POST / HTTP/1.1" 200 45 - "python-requests/2.25.1"
CheckModel (CheckModelCommand {checkModelModel = ModelDef {modelDefSource = Inline "model SIR:\n  let beta = 0.4\n  let gamma = 0.04\n\n  let s_initial = 997\n  let i_initial = 3\n  let r_initial = 0\n\n  state S = s_initial\n  state I = i_initial\n  state R = r_initial\n\n  let total_population = S + I + R\n\n  assert total_population == s_initial + i_initial + r_initial # total population is constant\n\n  event Infect:\n    rate: \n      beta * S * I / total_population\n    effect:\n      S -= 1\n      I += 1\n      \n  event Remove:\n    rate: \n      gamma * I\n    effect:\n      I -= 1\n      R += 1\n      \n      ", modelDefType = AskeeModel}})
127.0.0.1 - - [01/Jun/2021:13:40:12 -0400] "POST / HTTP/1.1" 200 45 - "python-requests/2.25.1"
CheckModel (CheckModelCommand {checkModelModel = ModelDef {modelDefSource = Inline "model SIR:\n  let beta = 0.4\n  let gamma = 0.04\n\n  let s_initial = 997\n  let i_initial = 3\n  let r_initial = 0\n\n  state S = s_initial\n  state I = i_initial\n  state R = r_initial\n\n  let total_population = S + I + R\n\n  assert total_population == s_initial + i_initial + r_initial # total population is constant\n\n  event Infect:\n    rate: \n      beta * S * I / total_population\n    effect:\n      S -= 1\n      I += 1\n      \n  event Remove:\n    rate: \n      gamma * I\n    effect:\n      I -= 1\n      R += 1\n      \n      ", modelDefType = AskeeModel}})
127.0.0.1 - - [01/Jun/2021:13:40:40 -0400] "POST / HTTP/1.1" 200 45 - "python-requests/2.25.1"
Stratify (StratifyCommand {stratModel = Inline "model SIR:\n  let beta = 0.4\n  let gamma = 0.04\n\n  let s_initial = 997\n  let i_initial = 3\n  let r_initial = 0\n\n  state S = s_initial\n  state I = i_initial\n  state R = r_initial\n\n  let total_population = S + I + R\n\n  assert total_population == s_initial + i_initial + r_initial # total population is constant\n\n  event Infect:\n    rate: \n      beta * S * I / total_population\n    effect:\n      S -= 1\n      I += 1\n      \n  event Remove:\n    rate: \n      gamma * I\n    effect:\n      I -= 1\n      R += 1\n      \n      ", stratConnections = FromFile "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/jupyter2/connectionGraph/cities.txt", stratStates = Nothing, stratType = Spatial})
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8001: Connection refused
```

The use of port 8001 is suspicious.

**Comment by RyanGlScott** [comment]
I was doing some parts of this wrong, as I wasn't running the Julia web server added in #5. Still, even after starting that, the `stratifySpatial` command above ultimately fails due to:

```
Traceback (most recent call last):
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 646, in do_execute
    self.interpreter.evalStmt(parsed, outputs)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 608, in evalStmt
    self.env[stmt.name] = self.evalExpr(stmt.expr, output)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 602, in evalExpr
    return self.callFn(expr, output)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 563, in callFn
    return self.builtins[call.functionName](call, output)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 327, in stratifySpatial
    stratResult = self.donu.stratifySpatial(model.source, cgraph.value, call)
  File "/home/rscott/Documents/Hacking/Haskell/ASKE-E/jupyter/impl/askeekernel.py", line 233, in stratifySpatial
    return self.request(req)['model']
KeyError: 'model'
```

**Comment by RyanGlScott** [comment]
Ah, this is because the JSON API changed commit 282d43c779569756f4d907de8224871c3b2c8dd4, so what used to be called `model` is now called `raw-model`. This is easy enough to fix.

**Comment by RyanGlScott** [comment]
All better now:

```
> sea_pdx_sir = stratifySpatial(sirESL, "connectionGraph/cities.txt")

> sea_pdx_sir

model foo:
  state S_1 = hole_A
  state I_1 = hole_B
  state R_1 = hole_C
  state S_2 = hole_D
  state I_2 = hole_E
  state R_2 = hole_F
  event diff_S_1_S_2:
    rate:
      hole_G
    effect:
      S_1 = S_1 - 1.0
      S_2 = S_2 + 1.0
  event diff_I_1_I_2:
    rate:
      hole_H
    effect:
      I_1 = I_1 - 1.0
      I_2 = I_2 + 1.0
  event diff_R_1_R_2:
    rate:
      hole_I
    effect:
      R_1 = R_1 - 1.0
      R_2 = R_2 + 1.0
  event diff_S_2_S_1:
    rate:
      hole_J
    effect:
      S_2 = S_2 - 1.0
      S_1 = S_1 + 1.0
  event diff_I_2_I_1:
    rate:
      hole_K
    effect:
      I_2 = I_2 - 1.0
      I_1 = I_1 + 1.0
  event diff_R_2_R_1:
    rate:
      hole_L
    effect:
      R_2 = R_2 - 1.0
      R_1 = R_1 + 1.0
  event Infect_1:
    rate:
      hole_M
    effect:
      S_1 = S_1 - 1.0
      I_1 = I_1 + 1.0
  event Remove_1:
    rate:
      hole_N
    effect:
      I_1 = I_1 - 1.0
      R_1 = R_1 + 1.0
  event Infect_2:
    rate:
      hole_O
    effect:
      S_2 = S_2 - 1.0
      I_2 = I_2 + 1.0
  event Remove_2:
    rate:
      hole_P
    effect:
      I_2 = I_2 - 1.0
      R_2 = R_2 + 1.0
```
